// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itveervvynitoqifxmjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0dmVlcnZ2eW5pdG9xaWZ4bWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDI1NTUsImV4cCI6MjA3NDIxODU1NX0.QoAMkzJk50gpNSDk7xvNSnm4-Dqo_KEdKf58Of6NyXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});